# Generated by Django 3.2.4 on 2022-03-26 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('nome', models.CharField(help_text='Nome da igreja. Pode ser um nome simbólico que faça sentido, como por exemplo "Matriz".', max_length=50, primary_key=True, serialize=False, verbose_name='Nome')),
                ('nome_normalizado', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do evento. Ex: "Culto de Adoração".', max_length=100, verbose_name='Nome')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('igreja', models.ForeignKey(help_text='Igreja onde o evento ocorrerá.', on_delete=django.db.models.deletion.CASCADE, to='programacao.igreja')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacao.igreja')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
