# Generated by Django 3.2.4 on 2021-07-02 22:47

from django.db import migrations
from datetime import date

def create_data(apps, schema_editor):
    Programacao = apps.get_model('programacao', 'Programacao')
    Programacao(nome="Oração Matutina", data=date.today()).save()


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
