# Generated by Django 3.2.4 on 2022-03-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igreja',
            name='nome_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
