# Generated by Django 3.2.4 on 2021-07-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0002_programacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programacao',
            new_name='Evento',
        ),
    ]
