# Generated by Django 3.2.4 on 2021-07-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0003_rename_programacao_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
