# Generated by Django 3.2.4 on 2021-07-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0004_alter_evento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(verbose_name='Data'),
        ),
    ]
