# Generated by Django 3.2.4 on 2023-02-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='nome_normalizado',
            new_name='igreja_normalizado',
        ),
    ]
